### ISSUE TITLE
Aplly the code on a bag file

### ISSUE THREAD

**Issue by RabahZeroukhi** [Photogrammetry-Robotics-Bonn/depth_clustering#11]
Hello, 
I want to apply the program on a .bag file recorded from velodyne 32HDL with /velodyne_points topic,
how can I manage to get it? which node should I use? 
thanks very much.

**Comment by niosus** [comment]
Sorry for the delay. I have missed your issue. I have examples in the `examples` folder. You need to run the node [show_objects_node](https://github.com/Photogrammetry-Robotics-Bonn/depth_clustering/blob/master/examples/ros_nodes/show_objects_node.cpp). Please follow the link to see which parameters you would need. It should work out of the box.
