### ISSUE TITLE
I have a 16 line VELODYNE lidar. How can I directly access this system?

### ISSUE THREAD

**Issue by ytgcljj** [Photogrammetry-Robotics-Bonn/depth_clustering#12]
I have a 16 line VELODYNE lidar. How can I directly access this system?

**Comment by niosus** [comment]
Hey @ytgcljj you should be able to use [this node](https://github.com/Photogrammetry-Robotics-Bonn/depth_clustering/blob/master/examples/ros_nodes/show_objects_node.cpp) if you can record a ROS bag file with your VLP 16.
