### ISSUE TITLE
If I only want to detect vehicles and pedestrians, which places should I configure?

### ISSUE THREAD

**Issue by PanZhichen** [Photogrammetry-Robotics-Bonn/depth_clustering#22]
![2](https://user-images.githubusercontent.com/23658856/38197461-c77dd97e-36ba-11e8-9aa2-737222fba3bc.png)

In the picture above, there are vehicles, pedestrians, trees and wall. I want to detect only vehicles and pedestrians, do you have any suggestions for my idea?
Looking forward to your reply, thanks:)

**Comment by niosus** [comment]
There is no way to do it with this piece of code as it just does segmentation and knows nothing about the semantics. Semantics is an interesting step that can come on top of clustering, but is out of the scope of this method.

**Comment by tejalbarnwal** [comment]
@niosus @PanZhichen are there any methods that could be used to do the same and get the bounding boxes as well?
